### ISSUE TITLE
BinNormalisation can fail because of originating_system

### ISSUE THREAD

**Issue by KrisThielemans** [KrisThielemans/STIR#1]
`ExamInfo::operator==` checks for `originating_system` but this is not uniquely defined .For instance, @evgueni-ovtchinnikov [reported a case](https://github.com/SyneRBI/SIRF/issues/926#issuecomment-844185647_) where `this->originating_system` was `2008`, and `p1.originating_system` was `Siemens mMR`.

@danieldeidda, shall we remove it from the comparison? `BinNormalisation` will check for `proj_data_info` anyway. If we do, we should document that we're not checking it.

**Comment by KrisThielemans** [comment]
wrong repo

**Comment by danieldeidda** [comment]
Hi sorry just came back. I am catching up with these!
